### ISSUE TITLE
Very useful, but doesn't work :(

### ISSUE THREAD

**Issue by agostinocinelli** [daixinkai/AspNetCore.Owin#1]
Hi,
i found this library on nuget and downloaded all repo, but the sample project doesn't work as expected.
I obviously replaced &lt;machineKey /&gt; XML
I tried to access /api/values/ with the correct Authorization/Bearer headers, but the response is 
```
[value1, value2, null]
```
Did I miss smt?
Thank you for your help and work!

**Comment by daixinkai** [comment]
you can see this page that it worked，i did not write any name to the Authorization，please see  User property in the Controller。

**Comment by daixinkai** [comment]
> Hi,
> i found this library on nuget and downloaded all repo, but the sample project doesn't work as expected.
> I obviously replaced <machineKey /> XML
> I tried to access /api/values/ with the correct Authorization/Bearer headers, but the response is
> 
> ```
> [value1, value2, null]
> ```
> Did I miss smt?
> Thank you for your help and work!

you can see this page that it worked，i did not write any name to the Authorization，please see User property in the Controller。
