### ISSUE TITLE
Machine Key Unprotect issue

### ISSUE THREAD

**Issue by jsmith614** [daixinkai/AspNetCore.Owin#2]
Hi, I'm attempting to use this but am running into an error when trying to unprotect. It appears to protect and unprotect ok on a same request, but if I protect in one request, then unprotect the same string in another request, it fails. 

I was looking through the source code and saw that dataProtectoryType is never specified in your examples, but you're using it in the factory. Is this ok to leave null?

**Comment by jsmith614** [comment]
Ah, it appears that my encoding was the issue. I'm not sure what I was doing incorrectly, but I just discovered there is an overload for Protect/Unprotect that takes a string and used that instead. Whatever encoding it's doing there seems to be working. I was using Encoding.Default.GetBytes and Encoding.Default.GetString, which seems to have been causing the issue.

**Comment by daixinkai** [comment]
> Ah, it appears that my encoding was the issue. I'm not sure what I was doing incorrectly, but I just discovered there is an overload for Protect/Unprotect that takes a string and used that instead. Whatever encoding it's doing there seems to be working. I was using Encoding.Default.GetBytes and Encoding.Default.GetString, which seems to have been causing the issue.

Hi, This is the code in .NET Framework System.Web:
[https://referencesource.microsoft.com/#System.Web/Security/MachineKey.cs,d6594833e109d2fb](https://referencesource.microsoft.com/#System.Web/Security/MachineKey.cs,d6594833e109d2fb)
[https://referencesource.microsoft.com/#System.Web/Security/Cryptography/MachineKeyDataProtectorFactory.cs,cc110253450fcb16](https://referencesource.microsoft.com/#System.Web/Security/Cryptography/MachineKeyDataProtectorFactory.cs,cc110253450fcb16)
